# Generated by Django 2.0 on 2017-12-17 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Qfxcinema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
    ]
